version: 0.2
run-as: root
phases:
  install:
     runtime-versions: 
       docker: 18
     commands:
       - echo "Java project build is in install phase"
       - echo "installing open JDK"
       - yum -y install java-1.8.0-openjdk-devel
       - yum -y update
       - yum -y install yum-utils
       - yum -y groupinstall development
       - yum -y install https://centos7.iuscommunity.org/ius-release.rpm
       - yum -y install python36u
       - yum -y install python36u-pip
       - pip3.6 install --upgrade pip
       - pip3.6 install --upgrade awscli
  build:
    commands:
       - echo "build phase started...compiling java project"
       - javac Simple.java
       - echo "Executing java project"
       - java Simple
