version: 0.2
run-as: root
phases:
  install:
     runtime-versions: 
       docker: 18
     commands:
       - echo "Java project build is in install phase"
       - echo "installing open JDK"
       - yum -y install java-1.8.0-openjdk-devel
       - yum -y install java-1.8.0-openjdk 
  build:
    commands:
       - echo "build phase started...compiling java project"
       - javac Simple.java
       - echo "Executing java project"
       - java Simple
artifacts:
  secondary-artifacts:
    artifact1:
       base-directory: https://s3.console.aws.amazon.com/s3/buckets/myapp-java-artifacts/
       files:
          - Simple.class
